name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          echo "${{ secrets.EC2_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy Code to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@44.204.241.246 << 'EOF'
            cd /home/ec2-user/frontend-app/frontend  # or wherever your app lives
            git pull origin main
            sudo cp /home/ec2-user/frontend-app/frontend/leetcode_tracker/listproblems.html  /usr/share/nginx/html/leetcode_tracker/
            sudo cp /home/ec2-user/frontend-app/frontend/todo/todo.html  /usr/share/nginx/html/todo/
          EOF
